### ISSUE TITLE
Timescale Bug

### ISSUE THREAD

**Issue by Blargzargo** [starburst997/notessimo-issues#1]
As previously pointed out by Antonim on Discord, _U.N. Owen was Her?_ has a lot of awkward pauses in it. I'm 99.9% sure this is due to the timescale not being 1. On a side note, V3 was also a bit iffy about timescale, opening the song in the composer shows that the sheets actually overlap because the end position of the sheet is reported incorrectly.

https://www.notessimo.net/page/browse/songs.html/_/video-games/other3/un-owen-was-her-r77326

**Comment by starburst997** [comment]
Thanks! Yes any songs using “timescale” would be inaccurate in V4 currently, I forgot to implement that one. I’ll try to fix that this week!

**Comment by starburst997** [comment]
[Through the fire and flames](https://www.notessimo.net/page/browse/songs.html/_/cover/00/through-the-fire-and-flames-r77235) might be related to the same issue.

"Completely messed up, sheets overlap and get out of sync, vocals get out of sync, random empty spots and even weird tempo changes in some sheets?"

"But ye, sheets with conflicting speeds seem to work weird"

**Comment by starburst997** [comment]
Timescale is fine now, TTFAF issue: https://github.com/starburst997/notessimo-issues/issues/23
