### ISSUE TITLE
Samples not looping correctly

### ISSUE THREAD

**Issue by starburst997** [starburst997/notessimo-issues#11]
[A billion bodies](https://www.notessimo.net/page/browse/songs.html/_/metal-rock/other4/a-billion-bodies-r74000), "I had a clock tick sound at 1:32 and it just stops"

**Comment by Antonim54** [comment]
[Whirlpool Man](https://www.notessimo.net/page/browse/songs.html/_/video-games/mega-man/mega-man-unlimited-enigma-of-aqua-whirlpool-man-r76960): Gameboy sample is slow on the attack on lower notes, also slightly flat. Keep in mind I also used CyanSM64's Gameboy sample, which is a different instrument entirely.

**Comment by Antonim54** [comment]
[Centaur Man](https://www.notessimo.net/page/browse/songs.html/_/video-games/mega-man/mega-man-6-ancient-city-centaur-man-r74617): Acoustic Bass lacks sustain.

**Comment by starburst997** [comment]
Test case added, still not fixed, will probably require converting the entire DB again

**Comment by starburst997** [comment]
Should be fixed (in next update)! Please feel free to re-open this issue if it's not!
