### ISSUE TITLE
Sheet Key not implemented?

### ISSUE THREAD

**Issue by Antonim54** [starburst997/notessimo-issues#18]
Just want to confirm something. I remember in my early experience with V3 that I briefly experimented with the "Key" functionality in the Sheet settings. Evidently, this wasn't popular among the community, but it looks like the V4 update doesn't take it into account either. As a result, songs like this are playing different notes in different places: https://www.notessimo.net/page/browse/songs.html/_/video-games/nintendo/super-smash-bros-brawl-bramble-blast-dkc2-r75459

**Comment by starburst997** [comment]
Thanks! I did implemented it in V4 but never properly tested it so I must've forgotten something, having a test case will make this easy to debug!!

**Comment by starburst997** [comment]
Should be fixed! Please feel free to re-open this issue if it's not!
