### ISSUE TITLE
Fade-In bug

### ISSUE THREAD

**Issue by Antonim54** [starburst997/notessimo-issues#19]
So this issue has actually popped up in V3 also. Basically, notes with a set _Fade In_ value and without a _Fade Out_ value only play the _Fade In_ portion of the note and then go mute. [Case in point.](https://www.notessimo.net/page/browse/songs.html/_/electronic/dance/up-there-in-macadamia-original-mix-r75411)

**Comment by starburst997** [comment]
Awwwwwwwwwwwwww!! Thanks!

**Comment by starburst997** [comment]
Should be fixed! Please feel free to re-open this issue if it's not!
