### ISSUE TITLE
Missing/muted/improperly tuned instruments

### ISSUE THREAD

**Issue by Antonim54** [starburst997/notessimo-issues#2]
I've noticed a number of instruments in the v4 player that haven't been properly tuned or are just outright missing. I've posted some examples in the Discord server, but here's another I found recently. Here, most of the piano chords are missing, the Electric Piano is muted, and the Steel Guitar is only playing C. Will continue listening for more buggy instruments.

https://www.notessimo.net/page/browse/songs.html/_/video-games/other3/rude-buster-r77779

**Comment by Antonim54** [comment]
Synth Oohs are out of tune
https://www.notessimo.net/page/browse/songs.html/_/video-games/nintendo/super-smash-bros-brawl-bramble-blast-dkc2-r75459

**Comment by starburst997** [comment]
Thanks! I remember testing this song specifically, I must've broke something recently, will look into it!

**Comment by Antonim54** [comment]
[User exercise](https://www.notessimo.net/page/browse/songs.html/_/miscellaneous/collabs/user-exercise-unf-and-prob-never-will-be-r75051): Sheet "Ashley 3" - Power Snare 2 inaudible, Standard Snare 3 missing

**Comment by Antonim54** [comment]
[Victory Road](https://www.notessimo.net/page/browse/songs.html/_/video-games/nintendo/pok%c3%a9mon-rse-victory-road-r73288) - French Horn and Harpsichord 1 inaudible

**Comment by Antonim54** [comment]
[Another Medium](https://www.notessimo.net/page/browse/songs.html/_/video-games/other3/undertale-another-medium-r75460) - Lead Guitar: some notes missing, later sheets disappear, most noticeable at 1:14 onwards

**Comment by Antonim54** [comment]
[Spark Engine](https://www.notessimo.net/page/browse/songs.html/_/video-games/other3/20xx-spark-engine-level-9-r74953) - Sine not properly tuned, see 1:00

**Comment by starburst997** [comment]
Should be fixed (in next update)! Please feel free to re-open this issue if it's not!
