### ISSUE TITLE
Brushes missing

### ISSUE THREAD

**Issue by Antonim54** [starburst997/notessimo-issues#21]
Another feature I briefly experimented with, which I'm hoping is a little more fleshed out in V4. https://www.notessimo.net/page/browse/songs.html/_/video-games/mega-man/mega-man-5-proto-mans-castle-dark-man-r73062

**Comment by starburst997** [comment]
Thanks! Unit Test added and failing, will be fixed shortly!

**Comment by starburst997** [comment]
Brushes should now be working! Please feel free to re-open this issue if it's not!
