### ISSUE TITLE
Instruments being off key

### ISSUE THREAD

**Issue by starburst997** [starburst997/notessimo-issues#9]
- [Plants Vs Zombies](https://www.notessimo.net/page/browse/songs.html/_/video-games/other3/plants-vs-zombies-cerebrawl-r77946), glockenspiel 
- [Mega Man 10](https://www.notessimo.net/page/browse/songs.html/_/video-games/mega-man/mega-man-10-nitro-rider-nitro-man-r67315), "1min mark, strat sample isn't properly tuned above D5"
- "i noticed the male vox in the jason mraz cover was detuned as well"
- [only my railgun](https://www.notessimo.net/page/browse/songs.html/_/themes/anime/only-my-railgun-tv-size-r45268), "flute is out of tune"
- [Ruins](https://www.notessimo.net/page/browse/songs.html/_/video-games/other3/undertale-ruins-r75404), "v3 glock is out of tune"

**Comment by Antonim54** [comment]
[20XX - Spark Engine](https://www.notessimo.net/page/browse/songs.html/_/electronic/dance/up-there-in-macadamia-original-mix-r75411): 1min mark, Sine is out of tune

**Comment by starburst997** [comment]
Should be fixed! Please feel free to re-open this issue if it's not!
